name: Test Project
on: [pull_request]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
 